####################################################################
####################################################################
####################################################################
#██    ██ ██    ██ ██      ██ ███    ███  █████  ██ ████████ ███████
#██    ██ ██    ██ ██      ██ ████  ████ ██   ██ ██    ██    ██
#██    ██ ██    ██ ██      ██ ██ ████ ██ ███████ ██    ██    █████
#██  ██   ██  ██  ██      ██ ██  ██  ██ ██   ██ ██    ██    ██
#████     ████   ███████ ██ ██      ██ ██   ██ ██    ██    ███████
####################################################################
####################################################################
####################################################################

#Plugin TPA - HLSMP

#Plugin kiểu DonutSMP TPA, bạn có thể chỉnh sửa toàn bộ tin nhắn trong lang.yml.

#permissions
#tpa.admin - quyền dùng các lệnh admin

#Tại đây bạn có thể chỉnh sửa toàn bộ tuỳ chọn của plugin
request-timeout: 30
teleport-delay: 5
cancel-on-move: true

world-nicknames:
  world: '&7Overworld'
  world_nether: '&7Nether'
  world_the_end: '&7End'

fly-status:
  true: 'Có'
  false: 'Không'

sound:
  teleport-cooldown: "block.note_block.pling"
  teleporting: "entity.enderman.teleport"
  button-click: "ui.button.click"
  teleport-success: "entity.player.levelup"
  teleport-fail: "entity.villager.no"
  reload: "entity.experience_orb.pickup"
